Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  # config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
    vb.cpus = 2
  end
end