Vagrant.configure("2") do |config|

  # Windows Server 2019
  config.vm.define "winserver" do |winserver|
    winserver.vm.box = "gusztavvargadr/windows-server-2019-standard"
    winserver.vm.hostname = "WindowsServer2019"
    winserver.vm.network "private_network", ip: "192.168.56.10"
    winserver.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
    end
  end

  # Windows 10
  config.vm.define "win10" do |win10|
    win10.vm.box = "gusztavvargadr/windows-10"
    win10.vm.hostname = "Windows10"
    win10.vm.network "private_network", ip: "192.168.56.11"
    win10.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

end
